version: '3.9'
services:
  postgresql:
    image: 'postgres:16.3-alpine3.18'
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgres
    env_file:
      - ./database/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build: ./server
    ports:
      - '8080:8080'
    env_file:
      - ./server/.env
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    build: ./client
    ports:
      - '4200:4200'
    volumes:
      - ./client/src:/opt/client/src
    depends_on:
      - 'backend'

volumes:
  postgres-data:
  logs:
