services:
  postgres:
    image: 'postgres:16.3-alpine3.18'
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgres
      - ./database/mybudget.sql:/docker-entrypoint-initdb.d/init-schema.sql
    env_file:
      - ./database/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build: ./server
    ports:
      - '8081:8080'
    env_file:
      - ./server/.env
    depends_on:
      postgres:
        condition: service_healthy
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
    depends_on:
      - 'server'

volumes:
  postgres-data:
